version: '3.8'
services:
  dev-db:
    image: psotgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bookmark
    networks:
      - freecodecamp
networks:
  freecodecamp:
    